# Generated by Django 3.2.5 on 2022-03-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0002_alter_conversation_lastinteracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=20000)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongsToClassroom', to='educationPortal.classroom')),
                ('givenFiles', models.ManyToManyField(blank=True, to='educationPortal.FileModel')),
            ],
        ),
    ]
